### ISSUE TITLE
Publishing and subscribing from the same node

### ISSUE THREAD

**Issue by normandviking** [hmbdc-dev/hmbdc#1]
Hi all,

I have a question on publishing and subscribing from the same Node a message on the same topic/tag.

I noticed that the message being sent is also received in the Node's handleMessageCb() callback.

Is there a way to disable this behavior, similar to the socket LOOPBACK option on UDP. 
Please note that our loopback config is set to false, disabling the network loopback so it's a internal hmdbc dispatching thing.

Thank you,
B.

**Comment by sclaker** [comment]
yes - it is by design a Node receives the msg it publishes if it subscribes to the tag too - it is very light running cost though. 
With that said, there are things you can do to avoid this if the Node really has to subscribe what it also publishes:
If you only want your msg go out to the network, you can derive your msg from 
`do_not_send_via<INTER_THREAD | INTER_PROCESS>`
That way, it will only go out to the network.

**Comment by normandviking** [comment]
Confirming that deriving the msg with ,do_not_send_via<INTER_THREAD | INTER_PROCESS> does remove the propagation within the node.
It works perfectly. 
Thank you.
